### ISSUE TITLE
rhel sane defaults

### ISSUE THREAD

**Issue by hoonetorg** [bechtoldt/saltstack-iscdhcp-formula#4]
checkout my changes with comments compared to current master (a2d9c08) on 
https://github.com/hoonetorg/saltstack-iscdhcp-formula/commits/develop
and tell me or merge :)

**Comment by bechtoldt** [comment]
Hi, when you already pushed code to Github, please create a PR. :)

The remark in the README file is for those who plan to make large code changes in the future.
